// Builds src/beef-ids.js: the ids of every TheMealDB recipe that contains beef, so category lists can
// leave them out without loading each recipe. Run again now and then to pick up new recipes:
//
//   node scripts/find-beef.mjs
//
// Opening a recipe, search and "Surprise me" also check the full ingredient list at runtime, so a
// recipe added after this list was made is still caught there.

import { writeFileSync } from "node:fs";
import { isBeefIngredient } from "../src/recipes.js";

const BASE = "https://www.themealdb.com/api/json/v1/1";
const get = async (path) => (await (await fetch(`${BASE}/${path}`)).json());

const ids = new Set();
const beef = await get("filter.php?c=Beef");
for (const meal of beef.meals ?? []) ids.add(meal.idMeal);

const { meals: allIngredients } = await get("list.php?i=list");
const beefIngredients = allIngredients.map((i) => i.strIngredient).filter(isBeefIngredient);
for (const name of beefIngredients) {
  const found = await get(`filter.php?i=${encodeURIComponent(name)}`);
  for (const meal of found.meals ?? []) ids.add(meal.idMeal);
}

const sorted = [...ids].sort((a, b) => Number(a) - Number(b));
writeFileSync(
  new URL("../src/beef-ids.js", import.meta.url),
  `// Generated by scripts/find-beef.mjs from ${beefIngredients.length} beef ingredients and the Beef category.\n` +
    `export const BEEF_IDS = new Set(${JSON.stringify(sorted)});\n`,
);
console.log(`${sorted.length} recipes with beef (ingredients: ${beefIngredients.join(", ")})`);
